# Generated by Django 3.1.7 on 2021-05-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_auto_20210517_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombres & Apellidos'),
        ),
    ]
